apiVersion: batch/v1
kind: Job
metadata:
  name: {python-job}
spec:
  template:
    spec:
      containers:
      - name: {python-job}
        image: markfjohnson/dev-python
        command: ["python3",  "-v", "{python-prog}"]
      restartPolicy: Never
  backoffLimit: 4
