---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wls-benefits-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wls-benefits-deployment
    spec:
      containers:
      - name: weblogic12
        image: markfjohnson/wls_benefits_k8s
        ports:
        - containerPort: 8001
        command: ["/bin/sh", "-c", "env|sort && ls -lt && pwd && bash startWebLogic.sh"]


---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: wls-benefits-service
  name:  wls-benefits-service
spec:
  ports:
    # The port that this service should serve on.
    - port: 8001
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: wls-benefits-deployment
  type: ClusterIP
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
        args:
        - --web
        - --kubernetes
      nodeSelector:
        kubernetes.dcos.io/node-type: public
      tolerations:
      - key: "node-type.kubernetes.dcos.io/public"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
  clusterIP: None
---
#Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: probe-ingress
spec:
  rules:
  - http:
      paths:
      - path: /wls
        backend:
          serviceName: wlsbenefitsservice
          servicePort: 10000